title: BBIS Developer Documentation
baseurl: /bbis
highlighter: true
permalink: /404.html
collections:
  reference:
    output: true
    permalink: /reference/:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      sidebar: true
      carousel: false