title: BBIS Developer Documentation
baseurl: /bbis
markdown: rdiscount
highlighter: true
permalink: /404.html
collections:
  getting_started:
    output: true
    permalink: /getting-started/:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      sidebar: true
      carousel: false